project:
  name: Application
  version: 0.1
  description: Phone Directory Application

server:
  port: 7080

spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    driverClassName: org.h2.Driver
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
    path: /h2-console